### ISSUE TITLE
Document Raspi Zero W wifi configuraiton

### ISSUE THREAD

**Issue by truedat101** [RazortoothRTC/raspizero-archlinux-base#2]
Ultimately I need an easy set of command line steps to configure wifi that is using WPA-2 Personal. 

General notes and links on wpa supplicant / linux:

https://wiki.netbsd.org/tutorials/how_to_use_wpa_supplicant/

https://wiki.archlinux.org/index.php/WPA_supplicant

https://donnutcompute.wordpress.com/2014/04/20/connect-to-wi-fi-via-command-line/

https://linuxconfig.org/setup-wireless-interface-with-wpa-and-wpa2-on-ubuntu

https://stackoverflow.com/questions/12899460/how-to-debug-wpa-supplicant-in-android

wpa_supplicant -B -iwlan0 -c/etc/wpa_supplicant.conf -d

**Comment by truedat101** [comment]
If we can set the docs up here, would be great: https://github.com/RazortoothRTC/raspizero-archlinux-base/wiki/ArchLinux-ARM-Raspi0-W-Wireless-Set-up-Guide

**Comment by existere** [comment]
Will do!

**Comment by existere** [comment]
I've installed and enabled/started NetworkManager but upon reboot I have to connect manually to wifi by initializing wpa_supplicant and dhcp. Is it necessary to have the rpi connect to wifi automatically? Ideally I would like NetworkManager to work but I'm not sure why it won't.

**Comment by truedat101** [comment]
yes, we want this to work on boot up, and without needing to configure a
GUI to make it work.

**Comment by existere** [comment]
I got it to work on bootup with configuring netctl!

**Comment by truedat101** [comment]
ok perfect.

**Comment by truedat101** [comment]
The docs look good.  I'll be testing this out probably in a week or so.

**Comment by truedat101** [comment]
I'll try testing this before thanksgiving time frame.

**Comment by truedat101** [comment]
So I've finished development on my application, I will be trying this out next week.

**Comment by truedat101** [comment]
Verified.  Noting, the raspi0 doesn't support N wiressless.
